# Generated by Django 4.2.11 on 2024-04-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctorprofile_doctor_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreport',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreport',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreport',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreport',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
