# Generated by Django 4.2.11 on 2024-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_patientprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='user',
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='dr_name',
            field=models.CharField(max_length=200),
        ),
    ]
